global using System.Linq.Expressions;
global using System.Text.RegularExpressions;
global using Luizanac.MongoDB.QueryExtensions.Abstractions.Interfaces;
global using Luizanac.MongoDB.QueryExtensions.Abstractions.Enums;
global using Luizanac.MongoDB.QueryExtensions.OrderBy;
global using static System.Console;
global using Luizanac.MongoDB.QueryExtensions.Filter;
global using System.Text;
global using MongoDB.Driver;
global using Luizanac.MongoDB.QueryExtensions.Extensions;
global using MongoDB.Bson;